import { Manrope } from "next/font/google";
import "../_assets/style/globals.css";
import Navbar from "../_components/layout/Navbar";
import { NextIntlClientProvider } from "next-intl";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});
export const metadata = {
  title: {
    default: "Moody",
    template: "%s | Moody",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await import(`@/src/i18n/messages/${locale}.json`).then(
    (m) => m.default,
  );
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${manrope.variable} h-full antialiased`}
    >
      {" "}
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
