import { Lora, Manrope } from "next/font/google";
import "../_assets/style/globals.css";
import Navbar from "../_components/layout/Navbar";
import { NextIntlClientProvider } from "next-intl";
import Provider from "../_providers/Provider";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
});
// const freeSerif = Free;
export const metadata = {
  title: {
    default: "Moody",
    template: "%s | Moody",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await import(`@/src/i18n/messages/${locale}.json`).then(
    (m) => m.default,
  );
  const dir = locale === "ar" ? "rtl" : "ltr";
  return (
    <html
      lang={locale}
      dir={dir}
      className={`${manrope.variable} ${lora.variable} h-full antialiased`}
    >
      {" "}
      <body className="">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Provider>
            <div className="min-h-full flex flex-col">{children}</div>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
